define(['knockout', '../services/creditOfficerService', '../services/documentService', '../services/authService', '../utils/storage', '../utils/constants', '../utils/errorMessages', 'ojs/ojrouter'], function (ko, creditOfficerService, documentService, authService, storage, constants, errorMessages, Router) {
    'use strict';
    function CreditOfficerDashboardViewModel() {
        const self = this;
        self.user = ko.observable(storage.getUser()); self.applications = ko.observableArray([]); self.selectedApplication = ko.observable(null); self.selectedDocuments = ko.observableArray([]); self.isLoading = ko.observable(true); self.isProcessing = ko.observable(false); self.isOpeningDocument = ko.observable(false); self.errorMessage = ko.observable(''); self.successMessage = ko.observable('');
        self.pendingApplications = ko.pureComputed(function () { return self.applications().filter(function (item) { return item.status === 'SUBMITTED' || item.status === 'UNDER_REVIEW'; }); });
        self.approvedApplications = ko.pureComputed(function () { return self.applications().filter(function (item) { return item.status === 'APPROVED'; }); });
        self.reviewedCount = ko.pureComputed(function () { return self.applications().filter(function (item) { return item.status === 'UNDER_REVIEW'; }).length; });
        self.formatCurrency = function (value) { return new Intl.NumberFormat('en-IN', { style:'currency', currency:'INR', maximumFractionDigits:0 }).format(Number(value || 0)); };
        self.formatRisk = function (value) { return value === null || value === undefined ? '—' : (Number(value) * 100).toFixed(0) + '%'; };
        self.canDecide = function (item) { return item && (item.status === 'SUBMITTED' || item.status === 'UNDER_REVIEW'); };
        self.formatSize = function (value) { return value ? (Number(value) / 1024 / 1024).toFixed(2) + ' MB' : ''; };
        self.selectApplication = async function (item) { self.errorMessage(''); self.selectedDocuments([]); try { self.selectedApplication(await creditOfficerService.getApplication(item.applicationId)); } catch (error) { console.error('Application detail load failed:', error); self.errorMessage(errorMessages.forRequest(error, 'The application details could not be loaded.')); return; } try { const documents = await creditOfficerService.getApplicationDocuments(item.applicationId); self.selectedDocuments((documents || []).map(function (document) { return Object.assign({}, document, { displaySize:self.formatSize(document.fileSize) }); })); } catch (error) { console.error('Officer document list load failed:', error); self.errorMessage(error && error.status === 404 ? 'Document review is not available until the updated backend is restarted.' : errorMessages.forRequest(error, 'The application documents could not be loaded.')); } };
        self.openDocument = async function (document) { const application = self.selectedApplication(); if (!application || self.isOpeningDocument()) { return; } self.isOpeningDocument(true); self.errorMessage(''); try { const previewUrl = await documentService.getDocumentPreviewUrl(application.applicationId, document.id); const previewWindow = window.open(previewUrl, '_blank'); if (!previewWindow) { window.location.assign(previewUrl); } window.setTimeout(function () { URL.revokeObjectURL(previewUrl); }, 60000); } catch (error) { console.error('Officer document preview failed:', error); self.errorMessage(errorMessages.forRequest(error, 'The document preview could not be opened.')); } finally { self.isOpeningDocument(false); } };
        self.approve = async function () { const item = self.selectedApplication(); if (!self.canDecide(item) || self.isProcessing()) { return; } self.isProcessing(true); self.errorMessage(''); self.successMessage(''); try { const issued = await creditOfficerService.approve(item.applicationId); self.successMessage('Application approved. Card ending ' + String(issued.maskedCardNumber || '').slice(-4) + ' was issued with a limit of ' + self.formatCurrency(issued.creditLimit) + '.'); self.selectedApplication(null); self.selectedDocuments([]); await self.loadApplications(); } catch (error) { console.error('Application approval failed:', error); self.errorMessage(errorMessages.forRequest(error, 'The application could not be approved.')); } finally { self.isProcessing(false); } };
        self.reject = async function () { const item = self.selectedApplication(); if (!self.canDecide(item) || self.isProcessing()) { return; } self.isProcessing(true); self.errorMessage(''); self.successMessage(''); try { await creditOfficerService.reject(item.applicationId); self.successMessage('Application ' + item.applicationNumber + ' has been rejected.'); self.selectedApplication(null); self.selectedDocuments([]); await self.loadApplications(); } catch (error) { console.error('Application rejection failed:', error); self.errorMessage(errorMessages.forRequest(error, 'The application could not be rejected.')); } finally { self.isProcessing(false); } };
        self.loadApplications = async function () { self.isLoading(true); try { self.applications(await creditOfficerService.getApplications() || []); } catch (error) { console.error('Officer queue load failed:', error); self.errorMessage(errorMessages.forRequest(error, 'The application queue could not be loaded.')); } finally { self.isLoading(false); } };
        self.logout = async function () { try { await authService.logout(); } finally { await Router.rootInstance.go('login'); } };
        self.initialize = async function () { const stored = storage.getUser(); if (!stored || (stored.role !== constants.ROLES.CREDIT_OFFICER && stored.role !== constants.ROLES.MANAGER)) { await Router.rootInstance.go('login'); return; } await self.loadApplications(); };
        self.initialize();
    }
    return CreditOfficerDashboardViewModel;
});
