spring.application.name=project
server.port=8080

# ============================================== DATABASE =============================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=project
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ============================================= JPA / Hibernate =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional: Explicit Oracle dialect (Hibernate usually detects it automatically)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ================================================== JWT =================================================

app.jwt.secret=${JWT_SECRET}

#900000 milliseconds = 15 minutes.
app.jwt.access-token-expiration=900000

# 30 days
app.jwt.refresh-token-expiration=2592000000

