package com.ofss.project.rag;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ofss.project.entity.CreditCardProduct;
import com.ofss.project.enums.CreditCardProductStatus;
import com.ofss.project.repository.CreditCardProductRepository;
import com.ofss.project.security.CurrentUser;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
@ConditionalOnProperty(prefix = "app.rag", name = "enabled", havingValue = "true")
public class RagService {

    private static final Logger log = LoggerFactory.getLogger(RagService.class);

    private static final String DISCLAIMER =
            "This is a fictional training recommendation, not financial advice.";

    private final CreditCardProductRepository productRepository;
    private final VectorStore vectorStore;
    private final ChatClient.Builder chatClientBuilder;
    private final CurrentUser currentUser;

    @Value("${app.rag.top-k:5}")
    private int topK;

    @Value("${app.rag.max-recommendations:3}")
    private int maxRecommendations;

    @Transactional(readOnly = true)
    public RagChatResponse chat(RagChatRequest request) {

        // Use JWT-backed identity. No user id is accepted from the client.
        currentUser.getUserId();

        boolean recommendationRequest =
                isRecommendationRequest(request.question());

        /*
         * Personalized recommendation requests require income and expense.
         */
        if (recommendationRequest
                && (request.income() == null || request.monthlyExpense() == null)) {

            return new RagChatResponse(
                    request.question(),
                    List.of(),
                    "Please provide your monthly income and monthly expense "
                            + "so I can compare suitable CredPulse cards. "
                            + DISCLAIMER,
                    DISCLAIMER);
        }

        /*
         * Relational DB is the authoritative source for eligibility.
         */
        List<CreditCardProduct> eligible =
                recommendationRequest
                        ? eligibleProducts(request.income())
                        : List.of();

        if (recommendationRequest
                && request.income() != null
                && eligible.isEmpty()) {

            return new RagChatResponse(
                    request.question(),
                    List.of(),
                    "No active CredPulse card currently matches the supplied "
                            + "monthly income. " + DISCLAIMER,
                    DISCLAIMER);
        }

        /*
         * Retrieve relevant RAG knowledge.
         */
        List<Document> retrieved;

        try {
            retrieved = vectorStore.similaritySearch(
                    SearchRequest.builder()
                            .query(request.question())
                            .topK(topK)
                            .build());
        } catch (RuntimeException ex) {
            throw new RagUnavailableException(
                    "RAG retrieval is unavailable", ex);
        }

        /*
         * Map eligible relational products by authoritative product code.
         */
        Map<String, CreditCardProduct> eligibleByCode =
                eligible.stream()
                        .collect(Collectors.toMap(
                                CreditCardProduct::getProductCode,
                                product -> product,
                                (first, ignored) -> first,
                                LinkedHashMap::new));

        /*
         * Structured recommendations are generated by Java.
         * Gemini does not invent this list.
         */
        List<RagRecommendation> recommendations =
                recommendationRequest
                        ? recommendations(
                                retrieved,
                                eligibleByCode,
                                request)
                        : List.of();

        /*
         * Gemini generates the natural-language explanation.
         */
        String answer = generateAnswer(
                request,
                eligible,
                retrieved,
                recommendationRequest,
                recommendations);

        log.info(
                "RAG chat completed: {} retrieved chunks, {} eligible cards, "
                        + "{} recommendations",
                retrieved.size(),
                eligible.size(),
                recommendations.size());

        return new RagChatResponse(
                request.question(),
                recommendations,
                answer,
                DISCLAIMER);
    }

    /**
     * Relational DB remains the authority for eligibility.
     */
    private List<CreditCardProduct> eligibleProducts(
            BigDecimal monthlyIncome) {

        List<CreditCardProduct> active =
                productRepository.findByStatusOrderByNameAsc(
                        CreditCardProductStatus.ACTIVE);

        if (monthlyIncome == null) {
            return active;
        }

        return active.stream()
                .filter(product ->
                        product.getMinimumIncome()
                                .compareTo(monthlyIncome) <= 0)
                .toList();
    }

    /**
     * Build structured recommendations.
     *
     * Ranking order:
     *
     * 1. Explicit user spending/category preference
     * 2. Relevance of retrieved card knowledge
     * 3. Lower annual fee as a mild tie-breaker
     * 4. Stable product name ordering
     *
     * Eligibility has already been enforced before this method is called.
     */
    private List<RagRecommendation> recommendations(
            List<Document> retrieved,
            Map<String, CreditCardProduct> eligibleByCode,
            RagChatRequest request) {

        /*
         * Map product code -> first retrieval rank.
         * The vector rank is only a secondary signal.
         */
        Map<String, Integer> retrievalRank = new LinkedHashMap<>();

        for (int index = 0; index < retrieved.size(); index++) {

            Object code =
                    retrieved.get(index)
                            .getMetadata()
                            .get("cardCode");

            if (code != null
                    && eligibleByCode.containsKey(code.toString())) {

                retrievalRank.putIfAbsent(
                        code.toString(),
                        index);
            }
        }

        /*
         * If there is no preference, don't pretend that arbitrary eligible
         * cards are the best cards.
         *
         * In that situation return no structured recommendations.
         * Gemini will explain that more spending information is required.
         */
        if (!hasSpendingPreference(request)) {
            return List.of();
        }

        /*
         * Rank only eligible products.
         */
        List<String> orderedCodes =
                new ArrayList<>(eligibleByCode.keySet());

        orderedCodes.sort((leftCode, rightCode) -> {

            CreditCardProduct left =
                    eligibleByCode.get(leftCode);

            CreditCardProduct right =
                    eligibleByCode.get(rightCode);

            int leftScore =
                    suitabilityScore(
                            left,
                            retrieved,
                            retrievalRank,
                            request);

            int rightScore =
                    suitabilityScore(
                            right,
                            retrieved,
                            retrievalRank,
                            request);

            if (leftScore != rightScore) {
                return Integer.compare(
                        rightScore,
                        leftScore);
            }

            /*
             * Vector retrieval is only a tie-breaker.
             */
            int leftRank =
                    retrievalRank.getOrDefault(
                            leftCode,
                            retrieved.size());

            int rightRank =
                    retrievalRank.getOrDefault(
                            rightCode,
                            retrieved.size());

            if (leftRank != rightRank) {
                return Integer.compare(
                        leftRank,
                        rightRank);
            }

            /*
             * Final stable tie-breaker.
             */
            return left.getName()
                    .compareToIgnoreCase(
                            right.getName());
        });

        return orderedCodes.stream()
                .limit(maxRecommendations)
                .map(code -> recommendation(
                        eligibleByCode.get(code),
                        suitabilityScore(
                                eligibleByCode.get(code),
                                retrieved,
                                retrievalRank,
                                request),
                        request))
                .toList();
    }

    /**
     * Calculate a simple deterministic suitability score.
     *
     * This is intentionally lightweight for the training project.
     *
     * The database determines eligibility.
     * The user preference determines suitability.
     * RAG retrieval acts as a supporting relevance signal.
     */
    private int suitabilityScore(
            CreditCardProduct product,
            List<Document> retrieved,
            Map<String, Integer> retrievalRank,
            RagChatRequest request) {

        int score = 0;

        String preference =
                request.preferredBenefit();

        if (preference != null && !preference.isBlank()) {

            String normalized =
                    preference.toLowerCase(Locale.ROOT);

            /*
             * Match the user's explicit preference against the actual RAG
             * knowledge belonging to this exact product code.
             */
            if (containsCardKnowledge(
                    product.getProductCode(),
                    retrieved,
                    normalized)) {

                score += 20;
            }

            /*
             * Add additional points for common category terms.
             */
            if (containsAny(
                    normalized,
                    "travel",
                    "flight",
                    "airport",
                    "lounge")) {

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "travel")) {

                    score += 20;
                }

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "lounge")) {

                    score += 10;
                }
            }

            if (containsAny(
                    normalized,
                    "shopping",
                    "online",
                    "ecommerce")) {

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "shopping")) {

                    score += 25;
                }
            }

            if (containsAny(
                    normalized,
                    "dining",
                    "restaurant",
                    "food")) {

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "dining")) {

                    score += 25;
                }
            }

            if (containsAny(
                    normalized,
                    "fuel",
                    "petrol",
                    "diesel")) {

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "fuel")) {

                    score += 25;
                }
            }

            if (containsAny(
                    normalized,
                    "cashback",
                    "cash back")) {

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "cashback")) {

                    score += 25;
                }
            }

            if (containsAny(
                    normalized,
                    "reward",
                    "rewards",
                    "points")) {

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "reward")) {

                    score += 25;
                }

                if (containsCardKnowledge(
                        product.getProductCode(),
                        retrieved,
                        "points")) {

                    score += 10;
                }
            }
        }

        /*
         * Vector similarity ranking is only a small supporting signal.
         */
        int rank =
                retrievalRank.getOrDefault(
                        product.getProductCode(),
                        retrieved.size());

        score += Math.max(
                0,
                5 - rank);

        /*
         * Lower annual fee is only a small tie-breaker.
         * It must never override a strong category preference.
         */
        if (product.getAnnualFee() != null
                && product.getAnnualFee()
                        .compareTo(BigDecimal.valueOf(1000)) <= 0) {

            score += 2;
        }

        return score;
    }

    /**
     * Checks whether the exact product's retrieved RAG knowledge contains
     * the requested term.
     */
    private boolean containsCardKnowledge(
            String productCode,
            List<Document> retrieved,
            String keyword) {

        String normalizedKeyword =
                keyword.toLowerCase(Locale.ROOT);

        return retrieved.stream()
                .filter(document ->
                        productCode.equals(
                                String.valueOf(
                                        document.getMetadata()
                                                .get("cardCode"))))
                .map(Document::getText)
                .map(text ->
                        text.toLowerCase(Locale.ROOT))
                .anyMatch(text ->
                        text.contains(normalizedKeyword));
    }

    private boolean containsAny(
            String text,
            String... values) {

        for (String value : values) {

            if (text.contains(value)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Builds the structured recommendation DTO.
     *
     * The reason is intentionally conservative:
     * eligibility is known from DB, suitability is supported by the
     * preference/retrieved context, but Java does not invent benefits.
     */
    private RagRecommendation recommendation(
            CreditCardProduct product,
            int score,
            RagChatRequest request) {

        String reason;

        if (hasSpendingPreference(request)) {

            reason =
                    "Eligible at the supplied income and ranked based on "
                            + "your stated spending preference and matching "
                            + "CredPulse card knowledge.";
        } else {

            reason =
                    "Eligible at the supplied income. Additional spending "
                            + "preferences are needed to determine the best fit.";
        }

        double normalizedScore =
                Math.min(
                        1.0d,
                        Math.max(
                                0.50d,
                                0.50d + (score * 0.02d)));

        return new RagRecommendation(
                product.getName(),
                product.getProductCode(),
                reason,
                normalizedScore);
    }

    /**
     * Generate the natural-language answer through Gemini.
     */
    private String generateAnswer(
            RagChatRequest request,
            List<CreditCardProduct> eligible,
            List<Document> retrieved,
            boolean recommendationRequest,
            List<RagRecommendation> recommendations) {

        if (retrieved.isEmpty()) {

            return "The available CredPulse knowledge does not contain "
                    + "enough relevant information to answer that question. "
                    + DISCLAIMER;
        }

        String candidates;

        if (recommendationRequest) {

            candidates =
                    eligible.stream()
                            .map(product -> String.format(
                                    Locale.ROOT,
                                    "%s (%s): minimum income %s, "
                                            + "annual fee %s, interest rate %s%%",
                                    product.getName(),
                                    product.getProductCode(),
                                    formatCurrency(
                                            product.getMinimumIncome()),
                                    formatCurrency(
                                            product.getAnnualFee()),
                                    product.getInterestRate()))
                            .collect(Collectors.joining("\n"));

        } else {

            candidates =
                    "None — this is an informational question.";
        }

        String profile;

        if (recommendationRequest) {

            profile =
                    "Income: "
                            + formatCurrency(request.income())
                            + "; monthly expense: "
                            + formatCurrency(request.monthlyExpense())
                            + "; expense ratio: "
                            + expenseRatio(request)
                            + "%\nTravel: "
                            + formatCurrency(request.travelExpense())
                            + "; shopping: "
                            + formatCurrency(request.shoppingExpense())
                            + "; dining: "
                            + formatCurrency(request.diningExpense())
                            + "; fuel: "
                            + formatCurrency(request.fuelExpense())
                            + "; preferred benefit: "
                            + valueOrNotProvided(
                                    request.preferredBenefit());

        } else {

            profile =
                    "Not provided — do not ask for financial details "
                            + "for a card-information question.";
        }

        String context =
                retrieved.stream()
                        .map(Document::getText)
                        .collect(Collectors.joining("\n---\n"));

        String structuredRecommendations;

        if (recommendations.isEmpty()) {

            structuredRecommendations =
                    "No structured recommendation has been selected yet. "
                            + "Do not invent one. If spending preference is "
                            + "missing, explain that more information is "
                            + "needed to distinguish suitable cards.";

        } else {

            structuredRecommendations =
                    recommendations.stream()
                            .map(recommendation ->
                                    recommendation.cardName()
                                            + " ("
                                            + recommendation.productCode()
                                            + ")")
                            .collect(Collectors.joining("\n"));
        }

        String instructions =
                recommendationRequest
                        ? """
                          This is a personalized recommendation request.

                          The backend has already applied the authoritative
                          eligibility rules.

                          Treat the "Structured Recommendations" section as
                          the cards selected by the backend.

                          Do not invent additional recommendations.

                          If structured recommendations are empty because the
                          user has not provided a useful spending preference,
                          do NOT pretend that arbitrary eligible cards are
                          the best choices.

                          Instead:
                          1. Explain briefly that the user meets eligibility
                             for available options.
                          2. Explain that income and total spending alone are
                             not enough to identify the best card.
                          3. Ask ONE useful question about their main spending
                             category.
                          4. Keep the answer concise.

                          If structured recommendations are present:
                          1. Lead with the strongest option.
                          2. Explain why it fits the user's stated preference.
                          3. Mention one relevant benefit from the retrieved
                             knowledge.
                          4. Mention one meaningful trade-off.
                          5. Mention another option only if it provides a
                             useful alternative.
                          6. Do not dump all eligible cards.
                          """
                        : """
                          This is an informational card question.

                          Answer the user's exact question directly.

                          Do not ask for income or expenses.

                          Mention only the facts needed to answer the question.

                          Do not turn an informational question into a
                          recommendation.
                          """;

        String prompt =
                "1. User Question\n"
                        + request.question()
                        + "\n\n2. User Profile\n"
                        + profile
                        + "\n\n3. Authoritative Eligible Cards\n"
                        + candidates
                        + "\n\n4. Structured Recommendations\n"
                        + structuredRecommendations
                        + "\n\n5. Retrieved CredPulse Card Knowledge\n"
                        + context
                        + "\n\n6. Instructions\n"
                        + instructions;

        try {

            return chatClientBuilder
                    .build()
                    .prompt()
                    .system(systemPrompt())
                    .user(prompt)
                    .call()
                    .content();

        } catch (RuntimeException ex) {

            log.error(
                    "LLM generation failed: exceptionClass={}, message={}",
                    ex.getClass().getName(),
                    ex.getMessage(),
                    ex);

            throw new RagUnavailableException(
                    "LLM response generation is unavailable",
                    ex);
        }
    }

    private String expenseRatio(
            RagChatRequest request) {

        return request.monthlyExpense()
                .multiply(BigDecimal.valueOf(100))
                .divide(
                        request.income(),
                        2,
                        RoundingMode.HALF_UP)
                .toPlainString();
    }

    private String systemPrompt() {

        return """
            You are the CredPulse Card Assistant for a fictional training
            application.

            Your job is to help users understand CredPulse cards and, when
            appropriate, help them choose a suitable card.

            Use only the information provided in:
            - User Question
            - User Profile
            - Authoritative Eligible Cards
            - Structured Recommendations
            - Retrieved CredPulse Card Knowledge

            The backend's eligibility results are authoritative.

            A card being eligible does not automatically mean it is the best
            or most suitable card.

            Never invent or guess:
            - card names
            - product codes
            - eligibility rules
            - fees
            - interest rates
            - credit limits
            - rewards
            - cashback
            - benefits
            - drawbacks
            - policies

            Never recommend a card that is not present in the authoritative
            backend data.

            For recommendation questions:
            - respect the structured recommendations selected by the backend
            - explain suitability using the user's stated preferences
            - use retrieved card knowledge to support benefits and trade-offs
            - do not claim that eligibility itself is a benefit
            - do not claim a card is best without sufficient evidence
            - if spending preferences are missing, explain that the
              recommendation is preliminary and ask one useful follow-up
            - do not dump every field of every card
            - do not invent a reason why a card is suitable

            For informational questions:
            - answer the exact question directly
            - do not ask for income or expenses
            - focus on relevant card information
            - do not turn the answer into a recommendation

            For comparison questions:
            - compare only the requested cards
            - focus on meaningful differences
            - use only supplied facts
            - do not invent a winner

            Response style:
            - conversational
            - concise
            - clear
            - helpful
            - customer-friendly
            - use ₹ for monetary values
            - prefer short paragraphs and useful bullets

            Do not sound like a database, technical report, or retrieved
            document.

            Never mention:
            - RAG
            - vector database
            - embeddings
            - retrieved chunks
            - prompts
            - internal metadata
            - backend implementation

            If information is unavailable, say so instead of guessing.

            All CredPulse cards and data are fictional training data and do
            not represent real financial products or financial advice.
            """;
    }

    private boolean hasSpendingPreference(
            RagChatRequest request) {

        if (request.preferredBenefit() != null
                && !request.preferredBenefit().isBlank()) {
            return true;
        }

        return hasAmount(
                        request.travelExpense())
                || hasAmount(
                        request.shoppingExpense())
                || hasAmount(
                        request.diningExpense())
                || hasAmount(
                        request.fuelExpense());
    }

    private boolean hasAmount(BigDecimal amount) {

        return amount != null
                && amount.compareTo(BigDecimal.ZERO) > 0;
    }

    private String formatCurrency(
            BigDecimal amount) {

        return amount == null
                ? "Not provided"
                : "₹"
                        + amount
                                .stripTrailingZeros()
                                .toPlainString();
    }

    private String valueOrNotProvided(
            String value) {

        return value == null
                || value.isBlank()
                        ? "Not provided"
                        : value.trim();
    }

    private boolean isRecommendationRequest(
            String question) {

        String normalized =
                question.toLowerCase(Locale.ROOT);

        return normalized.contains("recommend")
                || normalized.contains("best for me")
                || normalized.contains("should i choose")
                || normalized.contains("can i get")
                || normalized.contains("which card should")
                || normalized.contains("suitable for me");
    }
}